/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class monero_cpp_bridge_MoneroCppUtils */

#ifndef _Included_monero_cpp_bridge_MoneroCppUtils
#define _Included_monero_cpp_bridge_MoneroCppUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     monero_cpp_bridge_MoneroCppUtils
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_monero_cpp_1bridge_MoneroCppUtils_sayHello
  (JNIEnv *, jclass);

/*
 * Class:     monero_cpp_bridge_MoneroCppUtils
 * Method:    mapToBinary
 * Signature: (Ljava/util/Map;)[I
 */
JNIEXPORT jintArray JNICALL Java_monero_cpp_1bridge_MoneroCppUtils_mapToBinary
  (JNIEnv *, jclass, jobject);

/*
 * Class:     monero_cpp_bridge_MoneroCppUtils
 * Method:    binaryToMap
 * Signature: ([ILjava/util/Map;)V
 */
JNIEXPORT void JNICALL Java_monero_cpp_1bridge_MoneroCppUtils_binaryToMap
  (JNIEnv *, jclass, jintArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
